PARSER_BEGIN(HTML)

/** Simple brace matcher. */
public class HTML {

  /** Main entry point. */
  public static void main(String args[]) throws ParseException {
    HTML parser = new HTML(System.in);
    parser.Input();
  }

}

PARSER_END(HTML)

/** Root production. */
void Input() :
{}
{
  MatchedBraces() ("\n"|"\r")* <EOF>
}

/** Brace matching production. */
void MatchedBraces() :
{}
{
  "{" [ MatchedBraces() ] "}"
}
